### ISSUE TITLE
Output image seems to only be result of the first pass

### ISSUE THREAD

**Issue by dahston** [CauldronDevelopmentLLC/grabcut#5]
I'm sure I must be doing something wrong - when i use this, the Output preview window updates correctly to reflect the selections I am making. However when I save the image, the generated file does not match the image in the output preview window. 

The output file seems to be the result of the first grabcut pass (from drawing the blue rectangle) I can't get any updates to be saved to file, despite the output window accurately showing updated results.

I am using Python 3.7, numpy 1.17.2 and opencv-python 4.1.1.26

Please accept my apologies in advance, I am learning and it's entirely possible I am abusing your code in some way.

**Comment by dahston** [comment]
Here are the steps i took:

1. run command: grabcut.py [rupee.jpg][rupee] rupee_out.jpg
2. draw blue rectangle around image
3. make additional selections as necessary using 0 and 1 keys to draw areas of fg and bg
4. Output window looks like [this][outprev]
5. press s to save
6. [rupee_out.jpg][rupeeout] is not the same as the output preview window

This isn't the best example, because the saved file is probably a better result than the one i generated in my output window, but i just did this quickly to demonstrate that the output window and the generated output file are not the same for me.

Thank you for writing this code, and I hope this is valuable information.

[rupee]:https://i.imgur.com/SS32eGh.jpg
[rupeeout]:https://i.imgur.com/CdfNghw.jpg
[outprev]:https://i.imgur.com/Up7Ck1o.png

**Comment by dahston** [comment]
This is a result of me using the jpg file format and nothing at all to do with your code, jpg has no alpha channel which explains the rendered image being different.

If i output to png i have no such issue

I'm very sorry for any time wasted reading the nonsense above..

**Comment by jcoffland** [comment]
No problem.  There is a lot of room for improvement with this app.  It's not what I'd call user friendly.  I just put this up a couple of days ago.  Glad to see someone is using it already.
